### ISSUE TITLE
Create Placeholder data

### ISSUE THREAD

**Issue by bkidgamer1** [CS340-19/Synthony#9]
Using SQL for testing. Batch import CSV file into the SQL database.

**Comment by toddallen97** [comment]
Committed CSV files for the database.  While these files would normally be empty when the server has first been started, I have gone through and pretended to be a handful of students to create data.  Responses to professor questions were pulled from RateMyProfessor reviews.

The semesters that courses were offered may not be exact, but I tried to get it close (COSC402 is only in the Spring, COSC 401 in Fall, etc).
